### ISSUE TITLE
Still blocks of white when viewing your own profile

### ISSUE THREAD

**Issue by Mboxer511** [Jordy3D/Jordy3D.github.io#2] opened 2021-02-25 08:20 UTC
**Is your style request related to a problem? Please describe.**
When viewing your own profile, the sections where you can edit your info are still white

**Describe the solution you'd like**
The following additions to the CSS will fix this:

`/* ADDITIONAL EDITS */

.pv-profile-section.background-section.pv-profile-section--reorder-enabled .pv-profile-section .pv-profile-section__sortable-card-item {
    background-color: #1a2a33;
}

.pv-profile-section.background-section.pv-profile-section--reorder-enabled .pv-profile-section .pv-profile-section__card-item, .pv-profile-section.background-section.pv-profile-section--reorder-enabled .pv-profile-section .pv-profile-section__card-item-v2 {
    background-color: #1a2a33;
}

.pv-entity__position-group-pager {
    background: #162228 !important;
}

.ember-view {
    color: #ccc;
}

.theme--mercado .pv-recommendation-entity .lt-line-clamp__more {
    color: #999;
}`

**Describe alternatives you've considered**
A clear and concise description of any alternative styles you've looked at, if applicable.

**Additional context**

**Comment by Mboxer511** [comment] 2021-02-25 08:24
Also this code will fix the color of the 'see more' anchor links

.theme--mercado .pv-entity__extra-details .inline-show-more-text__button {
    color: #999;
}

.theme--mercado .pv-entity__extra-details .inline-show-more-text__button:hover {
    color: #ccc;
    text-decoration: underline;
}

**Comment by Jordy3D** [comment] 2021-02-25 08:38
Thank you for bringing an issue to my attention. However, you seem to have used the Issue Template for asking for a new style, rather than a failure of an existing one.

Based on some of the details I can see in those class names, am I correct in assuming this is the LinkedIn theme? You never actually mentioned anywhere, so I am with only the option to guess. I do have many styles listed on the site, after all.

Secondly, rather than using the term "still", it would be more accurate to use the term "now". Websites change, and CSS UserStyles will always be behind.

**Comment by Mboxer511** [comment] 2021-02-25 08:45
Yes this is for the LinkedIn theme, I was unaware I put this comment in the wrong section.  I thought this was the section to report an issue specific to the LinkedIn Userstyle. You're correct "now" would of been more proper.

**Comment by Jordy3D** [comment] 2021-02-25 08:53
This is the correct place for Issues, but not _specifically_ the LinkedIn theme. Over at [this link](https://jordy3d.github.io/banecss) you can see there are other styles here too. 
When you go to create an Issue, I believe Github prompts you with a choice of two Templates I have provided.

That said, I have added the lines you mentioned above (and some more changes you missed), and will push the update out when I get a chance, along with several other styles.
If it is still a problem after the new update is pushed, feel free to report back to this Issue. I will hold off on Closing the Issue for now, until it's confirmed working for now.

**Comment by Mboxer511** [comment] 2021-02-25 22:13
Thanks, when I clicked the link on this style over at UserStyles to report an issue it brought me directly here. That is why I thought it was the correct place to report a bug.

I'll keep a lookout for the new push.  If I notice any other bugs should I mention it here, or is there a link you can provide which directs me to the correct place to report an issue for the LinkedIn theme on github?

**Comment by Jordy3D** [comment] 2021-02-25 23:27
When you go to create a new Issue, I believe you see these two options
![image](https://user-images.githubusercontent.com/19144524/109232901-1cf2f000-781d-11eb-867d-e08c1a559fc7.png)
They each have descriptions of what they are intended for, and as such failures of an existing style are to use the upper Template. 

That said, since this Issue is already made, it would be best to keep future updates here.

**Comment by Jordy3D** [comment] 2021-03-08 06:08
I'll close this Issue as it seems like you've not found any other problems.
I believe two updates for the LinkedIn theme have gone live since this Issue was made, which I hope has corrected the issue.

**Closed as completed by Jordy3D** 2021-03-08 06:08 UTC
Labels: bug
